version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: address_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: address_db
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    container_name: address_redis
    restart: always
    ports:
      - '6379:6379'
